db-path: ./db.json

timeout: 10
paramiko:
  host: cn-relay.internet.limao.tech
providers:
  ok: https://rss.okxyz.xyz/link/zGjkzJeqP83WXt46?mu=2
  ww: https://xb1821.com/rss/mEWrAf3/CBQG7I?net_type=ALL

hosts:
  base: &base
    template: _base.yaml
    outbounds:
      - ok
      - ww
    extra-outbounds: []
  marf-bj:
    <<: *base
  marf-sh:
    <<: *base

github-proxy-release:
