[project]
name = "sing_tools"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.2",
    "ruff>=0.9.2",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.ruff.lint]
select = ["B", "E", "F", "I", "PGH"]
ignore = [
  "E501" # Line too long
]
